### PR TITLE
added flip board feature (reverse both dimensions)

### PR DESCRIPTION
**Pull request by Ghost-8D**
I could change it to flip only one dimension, but most of the times both dimensions are flipped in chess games.

### CODE REVIEW

**Comment by tanho63** [comment]
@timburgan this would be cool!

**Comment by timburgan** [comment]
:eyes: ohh i didn't see this

**Comment by mahapo** [comment]
> 👀 ohh i didn't see this

Probably because it's a @Ghost-8D

**Comment by timburgan** [comment]
Thanks for your suggestion. I'm going to merge it in 🎉

**Pull request merged**
