### PR TITLE
Contributed a few presentation aspects

### PR DESCRIPTION
**Pull request by DalpatRathore**

### CODE REVIEW

**Comment by DalpatRathore** [comment]
Hey! @timburgan 
   The changes I contributed can be seen in the given screenshots:
readmeshot-1
readmeshot-2
readmeshot-3

Thanks for developing and programming this game of minds.

**Comment by odil-io** [comment]
@DalpatRathore besides the two rows in the chart in your first screenshot, what else did you add?

**Comment by donno2048** [comment]
Please don't edit the _README.md_ by hand, only edit _.github/workflows/chess.yml_

**Comment by DalpatRathore** [comment]
@odil-io besides that changed headings as can be seen in the following screenshots.

**Comment by odil-io** [comment]
Ah now I see

**Comment by odil-io** [comment]
@DalpatRathore be sure to put the edits in https://github.com/timburgan/timburgan/blob/master/.github/workflows/chess.yml like donno2048 said. Readme.md gets overwritten every move.

**Comment by DalpatRathore** [comment]
hey! @odil-io   guide me, I don't know how does `.yml` works?

**Comment by odil-io** [comment]
@DalpatRathore don't worry, I'll put it in the right file for you. I'll make a new PR and mention you/this PR.

**Comment by odil-io** [comment]
Almost forgot to do this, so I just did.

**Comment by donno2048** [comment]
cc @timburgan

**Pull request closed without merging**
